from bertalign import Bertalign
# src = """抬头看时，只见山顶上一簇旗，旗丛中两把伞盖：左玄德，右孔明，二人对坐饮酒。许褚大怒，引军寻路上山。山上擂木炮石打将下来，不能前进。又闻山后喊声大震。欲寻路厮杀，天色已晚。曹仁领兵到，教且夺新野城歇马。军士至城下时，只见四门大开。曹兵突人，并无阻当，城中亦不见一人，竟是一座空城了。曹洪曰：“此是势孤计穷，故尽带百姓逃窜去了。我军权且在城安歇，来日平明进兵。”此时各军走乏，都已饥饿，皆去夺房造饭。曹仁、曹洪就在衙内安歇。初更已后，狂风大作。守门军士飞报火起。曹仁曰：“此必军士造饭不小心，遗漏之火，不可自惊。”说犹未了，接连几次飞报，西、南、北三门皆火起。曹仁急令众将上马时，满县火起，上下通红。是夜之火，更胜前日博望烧屯之火。后人有诗叹曰：“奸雄曹操守中原，九月南征到汉川。风伯怒临新野县，祝融飞下焰摩天。”曹仁引众将突烟冒火，寻路奔走，闻说东门无火，急急奔出东门。军士自相践踏，死者无数。曹仁等方才脱得火厄，背后一声喊起，赵云引军赶来混战，败军各逃性命，谁肯回身厮杀。正奔走间，糜芳引一军至，又冲杀一阵。曹仁大败，夺路而走，刘封又引一军截杀一阵。到四更时分，人困马乏，军士大半焦头烂额；奔至白河边，喜得河水不甚深，人马都下河吃水：人相喧嚷，马尽嘶鸣。"""

# tgt = """Chử vội ngẩng đầu lên, thấy trên đỉnh núi cắm một hàng cờ, trong đó có đôi lọng, bên tả thì Huyền Đức, bên hữu thì Khổng Minh ngồi đối diện uống rượu. Hứa Chử tức lắm, đem quân tìm đường lên núi, bị gỗ, đá ở trên lăn xuống, không tài nào lên được; lại nghe mé sau núi có tiếng reo rầm trời, định tìm lối đến đánh thì trời đã tối. Tào Nhân kéo quân đến, ra lệnh hãy cướp thành thì bốn cửa mở toang. Quân Tào xông vào không thấy ngăn trở; trong thành cũng không có một bóng người nào cả. Tào Hồng nói: - Lưu Bị gặp thế bí, nên đem cả trăm họ chạy trốn rồi, quân ta hãy tạm nghỉ lại, sáng mai sẽ tiến. Lúc này quân sĩ đều mệt và đói khát cả, liền tranh nhau thổi cơm ăn. Tào Nhân, Tào Hồng vào nghỉ trong huyện. Cuối canh một, gió to nổi lên. Lính gác chạy vào báo cháy. Tào Nhân nói: - Chắc quân sĩ thổi cơm, sơ ý để lửa cháy đấy thôi, không được xôn xao. Nói chưa dứt lời, Nhân lại liên tiếp nhận được tin ba cửa tây, nam, bắc đều bốc cháy. Khi Tào Nhân ra lệnh tất cả các tướng phải lên ngựa ngay, thì toàn huyện đã trở thành bể lửa bốc sáng rực trời. Lửa đêm hôm ấy lại cháy dữ hơn lửa đồn Bác Vọng hôm trước. Đời sau có thơ than rằng: Gian hùng Tào Tháo giữ Trung Nguyên Tháng chín sang năm đánh Hàn Xuyên Phong Bá ra oai huyện Tân Dã Chúc Dung bay xuống Diễm ma thiên Tào Nhân dẫn tướng tá xông pha khói lửa tìm đường chạy trốn. Thấy cửa đông không có lửa, Nhân vội vàng chạy ra phía đó. Quân sĩ giày xéo lẫn nhau, chết nhiều vô kể. Bọn Tào Nhân vừa thoát được nạn lửa thì đàng sau đã thấy ngay Triệu Vân dẫn quân đuổi đến đánh giết. Quân Tào tranh nhau chạy trốn, không ai dám ngoảnh cổ lại. Đang chạy, bị My Phương kéo quân ra bồi cho một trận nữa. Tào Nhân thua to, cướp đường rút chạy. Lưu Phong lại dẫn quân ra chặn đường, hai bên đánh nhau đến canh tư. Bấy giờ, người ngựa đều mệt, quân Tào phần lớn bị bỏng, sém trán, cháy đầu, chạy đến sông Bạch Hà, thấy nước sông không sâu, người ngựa hí hửng lội xuống uống nước, người thì ồn ào, ngựa thì gầm hí."""

# read src from chinese.txt 
src = open('chinese.txt', 'r', encoding='utf-8').read()
# read tgt from vietnamese.txt
tgt = open('vietnamese.txt', 'r', encoding='utf-8').read()
aligner = Bertalign(src, tgt)
aligner.align_sents()
aligner.print_sents()